### ISSUE TITLE
Add Exercise

### ISSUE THREAD

**Issue by ErazerBrecht** [ErazerBrecht/CodeGenie#3]
After we added an exercise, we reload every exercise.
This is done to load the id of the added exercise!

But it's better if the server answers with the id!

**Comment by ErazerBrecht** [comment]
This is done

I solved it by not only sending the id back, but everything. The deadline was also set on the backend!!

@ArneSchoonvliet 
Now you're also possible to check if the data has changes while transmitting!
Thanks for the tip!

**Comment by ArneSchoonvliet** [comment]
Sometimes I have some mad good ideas
